services:
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    restart: always
    environment:
      PIHOLE_PROTOCOL: http
      PIHOLE_HOSTNAME: ${PIHOLE_HOSTNAME}
      PIHOLE_PASSWORD: ${PIHOLE_PASSWORD}
      PORT: 9617
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
    ports:
      - 9617:9617
    networks:
      - monitoring-network
    
networks:
  monitoring-network:
    driver: bridge