[project]
name = "proxmox-exporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prometheus-client>=0.24.1",
    "proxmoxer>=2.2.0",
    "requests>=2.32.5",
]
