services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer 
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    init: true
    ports:
      - 80:80 
      - 8080:8080
    environment: 
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - SKIP_DOMAIN_VALIDATION=true

      - AIO_COMMUNITY_CONTAINERS: "local-ai memories" # Community containers https://github.com/nextcloud/all-in-one/tree/main/community-containers
      # - NC_TRUSTED_PROXIES: 172.18.0.3  # this is the NPM proxy ip address in the docker network !
      # - FULLTEXTSEARCH_JAVA_OPTIONS: "-Xms1024M -Xmx1024M"
      - NEXTCLOUD_DATADIR: /nextcloud/ncdata # ⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done!
      # - NEXTCLOUD_MOUNT: /mnt/ # Allows the Nextcloud container to access the chosen directory on the host.
      - NEXTCLOUD_UPLOAD_LIMIT: 1028G
      - NEXTCLOUD_MAX_TIME: 7200
      - NEXTCLOUD_MEMORY_LIMIT: 1028M
      # - NEXTCLOUD_ENABLE_DRI_DEVICE: true # Intel QuickSync
      # - TALK_PORT: 3478 # This allows to adjust the port that the talk container is using which is exposed on the host. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port

      

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer